# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
# You may pin to the exact commit or the version.
  # uses: PackagrIO/action-publishr-go@5500e68ee3673e8e8f9b825b72c67198d97804f3
  uses: PackagrIO/action-publishr-go@v1.0.1
  with:
    # Commit Author
    author_name: # default is packagrio-bot
    # Commit Author Email
    author_email: # default is packagr-io[bot]@users.noreply.github.com
    # Assets to upload
    upload_assets: # optional
    # Working Directory
    cwd: # optional, default is 
